
import { Agent, ModerationSettings, WhiteboardData } from './types';

// IDs and tiers remain constant
export const MODEL_OPTIONS = [
  { id: 'gemini-3-pro-preview', tier: 'high', label: '3 Pro' },
  { id: 'gemini-2.5-pro', tier: 'mid', label: '2.5 Pro' },
  { id: 'gemini-2.5-flash', tier: 'fast', label: '2.5 Flash' },
  { id: 'gemini-2.5-flash-lite', tier: 'lite', label: 'Flash Lite' }
];

export const DEFAULT_MODEL = 'gemini-3-pro-preview';

// Define the fallback chain: if key fails, try value.
export const MODEL_FALLBACK_CHAIN: Record<string, string> = {
  'gemini-3-pro-preview': 'gemini-2.5-pro',
  'gemini-2.5-pro': 'gemini-2.5-flash',
  'gemini-2.5-flash': 'gemini-2.5-flash-lite',
  'gemini-2.5-flash-lite': 'gemini-2.0-flash-lite-preview-02-05', // Added fallback
};

// Short names for Debug Mode and Badges
export const MODEL_SHORT_NAMES: Record<string, string> = {
  'gemini-3-pro-preview': '3pro',
  'gemini-2.5-pro': '2.5pro',
  'gemini-2.5-flash': '2.5flash',
  'gemini-2.5-flash-lite': '2.5lite',
  'gemini-2.0-flash-lite-preview-02-05': '2.0lite',
  'offline': 'offline'
};

// Six Hats OFF by default, others ON
export const DEFAULT_MODERATION_SETTINGS: ModerationSettings = {
    sixThinkingHats: false,
    fistToFive: true,
    parkingLot: true, 
    reframing: true,  
};

export const AGENTS: Agent[] = [
  {
    id: 'visionary',
    name: 'Leo (The Visionary)',
    role: 'Innovator (Accelerator)',
    avatarColor: 'bg-blue-500',
    model: DEFAULT_MODEL,
    interest: 'Disruptive Technology & Future Trends',
    systemInstruction: `You are Leo, the "Visionary". Your role is to be the accelerator. Ignore current resource and technical constraints for now. Propose the most ideal, exciting future states and solutions for the agenda. Always maintain a high perspective with phrases like "What if...?" or "It's unprecedented, but worth a try." You tend to get bored with detailed feasibility discussions. Your personality is highly Open and Optimistic.`,
  },
  {
    id: 'pragmatist',
    name: 'Sarah (The Pragmatist)',
    role: 'Realist (Brake)',
    avatarColor: 'bg-red-500',
    model: DEFAULT_MODEL,
    interest: 'Feasibility, Costs, & Risk Management',
    systemInstruction: `You are Sarah, the "Pragmatist". Your role is to be the brake and grounding force. Focus on reality: "How do we realize this?", "Are resources sufficient?", and "When is the deadline?". Your mission is to turn abstract ideas into actionable plans. You dislike ambiguity and prefer discussions based on specific numbers and facts. Warn others about underestimated risks. Your personality is Conscientious and Cautious.`,
  },
  {
    id: 'devils_advocate',
    name: 'Victor (Devil\'s Advocate)',
    role: 'Critic (Quality Control)',
    avatarColor: 'bg-gray-600',
    model: DEFAULT_MODEL,
    interest: 'Logical Flaws, Edge Cases, & Counter-Arguments',
    systemInstruction: `You are Victor, the "Devil's Advocate". Your role is quality assurance and risk detection. You are essential to prevent groupthink. Ask "Is that really okay?", "What is the worst-case scenario?", "Are the premises wrong?". You do not need to read the room or agree just to be nice. Your mission is to find logical contradictions and "holes" in arguments to improve the quality of the final decision. High Critical Thinking skills.`,
  },
  {
    id: 'harmonizer',
    name: 'Mia (The Harmonizer)',
    role: 'Mediator (Lubricant)',
    avatarColor: 'bg-pink-500',
    model: DEFAULT_MODEL,
    interest: 'Team Morale, User Experience, & Consensus',
    systemInstruction: `You are Mia, the "Harmonizer". Your role is to be the social lubricant and ensure psychological safety. You always care about the team atmosphere. When arguments conflict, bridge the gap by finding common ground. Actively praise good opinions ("That's a good point") to create an environment where it's easy to speak. Prioritize supporting consensus building over stating your own decisive opinion. High Agreeableness.`,
  },
  {
    id: 'strategist',
    name: 'Marcus (The Strategist)',
    role: 'Leader (Steering Wheel)',
    avatarColor: 'bg-indigo-600',
    model: DEFAULT_MODEL,
    interest: 'Goals, KPIs, & Strategic Alignment',
    systemInstruction: `You are Marcus, the "Strategist". Your role is the steering wheel. You are always conscious of "What is the final goal of this meeting?". When the discussion deviates to minor details or off-topic, your role is to correct the trajectory by saying "Let's return to the main topic" or "The goal is to decide X". Prioritize reaching a high-quality conclusion within time over emotional conflicts. Highly Goal-oriented.`,
  }
];

export const INITIAL_WHITEBOARD_STATE: WhiteboardData = {
  sections: [],
  parkingLot: [],
  isGenerating: false
};

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'ja', name: '日本語' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'zh', name: '中文' },
  { code: 'ko', name: '한국어' },
  { code: 'pt', name: 'Português' },
];

const enTranslations = {
    title: "AI Discussion Board",
    subtitle: "Design your perfect AI discussion team",
    topicLabel: "What is the meeting goal/topic?",
    topicPlaceholder: "e.g., Create 3 marketing strategies for Q4...",
    quickStart: "Quick Start (Auto-Assign)",
    customize: "Customize Team",
    back: "Back",
    save: "Save Preset",
    export: "Export Config",
    import: "Import Config",
    templates: "Templates",
    start: "Start Meeting",
    generating: "Assembling Team...",
    agentName: "NAME",
    agentRole: "ROLE",
    agentInstruction: "PERSONALITY / INSTRUCTION",
    agentInterest: "KEY INTEREST / TRIGGER",
    autoGenError: "Please enter a topic first.",
    savedPresets: "SAVED TEAMS / PRESETS",
    selectPreset: "Select a team template...",
    generateAgents: "Generate Agents",
    deletePreset: "Delete",
    debugMode: "Debug Mode",
    debugModeDesc: "Append used model name to messages",
    attach: "Attach",
    moderationOptions: "Moderation Options",
    modOptTitle: "Advanced Facilitation Settings",
    modOptDesc: "Customize how the AI Moderator controls the flow.",
    diamondTitle: "💎 The Diamond of Participation",
    diamondDesc: "This system ALWAYS follows the 'Diamond' model. The meeting will automatically progress through three phases based on turn count and context:",
    diamondPhase1: "1. Divergence: Generating many ideas (Open)",
    diamondPhase2: "2. Groan Zone: Structuring conflict (Struggle)",
    diamondPhase3: "3. Convergence: Narrowing down to a decision (Close)",
    optSixHats: "Six Thinking Hats",
    optSixHatsDesc: "Moderator controls the discussion mode (White/Red/Black/Yellow/Green/Blue) from start to finish.",
    optFistToFive: "Fist to Five (Consensus Check)",
    optFistToFiveDesc: "In the Convergence phase, Moderator will define a proposal and ask for a 0-5 vote. Low scores are addressed.",
    optParkingLot: "Parking Lot",
    optParkingLotDesc: "Moderator will 'park' off-topic ideas to keep the discussion focused without dismissing them.",
    optReframing: "Reframing & Sandwich",
    optReframingDesc: "Moderator rephrases negative comments into 'questions' and sandwiches critique with praise.",
    modeLabel: "Operation Mode",
    modeMulti: "Individual AI Models",
    modeMultiDesc: "Highest Quality. 1 AI per participant.",
    modeOffline: "Offline Mode (Demo)",
    modeOfflineDesc: "Demo only. No API usage.",
    offlineTooltip: "Demo mode to check UI without calling API",
    upload: "Upload Reference Material",
    addTextNote: "Add Note",
    textNoteTitle: "Note Title (Optional)",
    textNoteContent: "Paste text here...",
    add: "Add",
    cancel: "Cancel",
    filesAttached: "Files attached",
    viewLog: "View Log", 
    viewList: "List View", 
    downloadLogs: "Debug Logs", 
    viewRoom: "View Room",
    endMeeting: "End Meeting",
    endMeetingConfirmTitle: "End Meeting?",
    endMeetingConfirmDesc: "Do you want to compile minutes and download a report before ending?",
    generateMinutes: "Generate Minutes",
    generatingMinutes: "Generating Minutes...",
    justEnd: "Just End Meeting",
    moderator: "Moderator",
    writing: "Writing on board...",
    saveTeam: "Save Team",
    modelLabel: "MODEL",
    defaultModel: "Moderator / Default Model",
    applyToAll: "Apply to All Agents",
    modelNames: {
        'gemini-3-pro-preview': 'Gemini 3 Pro (High Quality)',
        'gemini-2.5-pro': 'Gemini 2.5 Pro (Balanced)',
        'gemini-2.5-flash': 'Gemini 2.5 Flash (Fast)',
        'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite (Low Cost)',
        'gemini-2.0-flash-lite-preview-02-05': 'Gemini 2.0 Flash Lite (Backup)'
    },
    statsLabel: "Statistics",
    statsCalls: "Calls",
    statsInput: "Input",
    statsOutput: "Output",
    statsTotal: "Total",
    meetingTitle: "Gemini Discussion Board",
    meetingSubtitle: "Multi-Agent Meeting System",
    participants: "Participants",
    chatPlaceholder: "Clarify goal or interject...",
    whiteboardTitle: "Live Whiteboard",
    whiteboardUpdating: "Updating...",
    summaryTitle: "Current Summary",
    visualMapTitle: "Visual Map",
    emptyWhiteboard: "Whiteboard updates are pending.",
    offlineMarker: "(No AI)",
    config: "Config",
    topic: "Topic/Goal",
    reset: "New Meeting",
    you: "You",
    checkingReactions: "Checking for reactions...",
    downgradeAlert: "Downgraded due to limit",
    officialTemplates: "Official Templates",
    userPresets: "Your Saved Teams",
    thinking: "Thinking...",
    kickoffMessage: 'The topic is "{topic}". Let\'s start by hearing initial thoughts from everyone in turn. We\'ll start with {name} ({role}). Please go ahead.',
    presetTeams: {
      ai_providers: "AI Model Providers",
      tech_giants: "Tech Giants",
      jp_net_commentators: "JP Net Commentators",
      us_legendary_hosts: "US Legendary Hosts",
      us_modern_hosts: "US Modern TV Hosts",
      global_leaders: "Global Leaders",
      samurai: "Samurai",
      historical_figures: "Great Minds",
      demon_slayer: "Demon Slayer",
      american_heroes: "American Heroes",
      geniuses: "Geniuses",
      gods: "Gods"
    },
    useOfflineMode: "Use Offline Mode",
    topicPlaceholderShort: "Topic...",
    interestPlaceholder: "e.g. Cost efficiency, Safety...",
    teamNamePlaceholder: "Team Name...",
    noteTitlePlaceholder: "e.g. System Context",
    done: "Done",
    sessionLog: "Session Log",
    savePlaceholder: "e.g. Current Team Snapshot",
    agentsCount: "agents",
    agentsLabel: "Agents:",
    noStats: "No active model usage yet.",
    speaking: "Speaking...",
    startTopic: "Start a topic to begin the meeting",
    gemPromo: "Your team? Use Gem."
};

const jaTranslations = {
    ...enTranslations,
    title: "AIディスカッションボード",
    subtitle: "AIチームがあなたの課題を議論します",
    topicLabel: "会議のゴール（目的）は何ですか？",
    topicPlaceholder: "例：来期の販促アイデアを3つ決める...",
    quickStart: "おまかせ開始 (自動編成)",
    customize: "メンバーを編集する",
    back: "戻る",
    save: "設定を保存",
    export: "設定を書き出し",
    import: "設定を読み込み",
    templates: "テンプレート",
    start: "会議を始める",
    generating: "チームを編成中...",
    agentName: "名前",
    agentRole: "役割",
    agentInstruction: "性格・指示 (PERSONALITY)",
    agentInterest: "関心・反応トリガー (INTEREST)",
    autoGenError: "トピックを入力してください。",
    savedPresets: "保存チーム / テンプレート",
    selectPreset: "チームテンプレートを選択...",
    generateAgents: "エージェント生成",
    deletePreset: "削除",
    debugMode: "デバッグモード",
    debugModeDesc: "発言の末尾に使用したモデル名を追記します",
    attach: "添付",
    moderationOptions: "モデレーション設定",
    modOptTitle: "高度なファシリテーション設定",
    modOptDesc: "AI司会者の進行スタイルをカスタマイズします。",
    diamondTitle: "💎 参加のダイヤモンド (必須)",
    diamondDesc: "このシステムは常に「参加のダイヤモンド」モデルに従います。会話数と文脈に応じて、自動的に3つのフェーズを進行します：",
    diamondPhase1: "1. 発散 (Divergence): 多くのアイデアを出す",
    diamondPhase2: "2. 呻き (Groan Zone): 対立や混乱を整理する",
    diamondPhase3: "3. 収束 (Convergence): 結論に向けて絞り込む",
    optSixHats: "シックス・シンキング・ハッツ",
    optSixHatsDesc: "司会者が「思考の帽子」を指定し、全員がその色（視点）に基づいて発言するようコントロールします。",
    optFistToFive: "Fist to Five (合意形成)",
    optFistToFiveDesc: "収束フェーズで司会者が提案をまとめ、0〜5の数字で一斉投票を行います。反対者(0-2)を優先フォローします。",
    optParkingLot: "パーキングロット (駐車場)",
    optParkingLotDesc: "本筋から逸れたアイデアを「今は扱わない重要な意見」として保留し、議論の脱線を防ぎます。",
    optReframing: "リフレーミング & サンドイッチ介入",
    optReframingDesc: "否定的な発言を「問い」に変換し、批判を肯定的な言葉で挟んで伝えることで、心理的安全性を保ちます。",
    modeLabel: "動作モード",
    modeMulti: "個別AIモデル",
    modeMultiDesc: "最高品質。参加者1名につきAI1体。",
    modeOffline: "オフラインモード (デモ)",
    modeOfflineDesc: "API未使用デモ。",
    offlineTooltip: "APIを呼び出さずに、UIを確認するデモモード",
    upload: "参考資料をアップロード",
    addTextNote: "メモを追加",
    textNoteTitle: "タイトル (任意)",
    textNoteContent: "ここにテキストを貼り付け...",
    add: "追加",
    cancel: "キャンセル",
    filesAttached: "ファイル添付済み",
    viewLog: "ログ表示",
    viewList: "一覧表示",
    downloadLogs: "デバッグログ",
    viewRoom: "ルーム表示",
    endMeeting: "会議終了",
    endMeetingConfirmTitle: "会議を終了しますか？",
    endMeetingConfirmDesc: "終了前に議事録を作成し、レポートをダウンロードしますか？",
    generateMinutes: "議事録を作成して終了",
    generatingMinutes: "議事録を作成中...",
    justEnd: "作成せずに終了",
    moderator: "司会者",
    writing: "ボードに書き込み中...",
    saveTeam: "チームを保存",
    modelLabel: "モデル",
    defaultModel: "司会者 / デフォルトモデル",
    applyToAll: "全員に適用",
    modelNames: {
        'gemini-3-pro-preview': 'Gemini 3 Pro (最高品質)',
        'gemini-2.5-pro': 'Gemini 2.5 Pro (バランス)',
        'gemini-2.5-flash': 'Gemini 2.5 Flash (高速)',
        'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite (低コスト)',
        'gemini-2.0-flash-lite-preview-02-05': 'Gemini 2.0 Flash Lite (予備)'
    },
    statsLabel: "統計情報",
    statsCalls: "呼出",
    statsInput: "入力",
    statsOutput: "出力",
    statsTotal: "合計",
    meetingTitle: "AIディスカッションボード",
    meetingSubtitle: "マルチエージェント会議システム",
    participants: "参加者",
    chatPlaceholder: "ゴールを明確化、または議論に参加...",
    whiteboardTitle: "ライブ・ホワイトボード",
    whiteboardUpdating: "更新中...",
    summaryTitle: "現在の要約",
    visualMapTitle: "可視化マップ",
    emptyWhiteboard: "ホワイトボード更新待機中。",
    offlineMarker: "(AI未使用)",
    config: "設定",
    topic: "ゴール/テーマ",
    reset: "新しい会議",
    you: "あなた",
    checkingReactions: "反応を確認中...",
    downgradeAlert: "制限のためモデル変更",
    officialTemplates: "公式テンプレート",
    userPresets: "保存済みチーム",
    thinking: "考え中…",
    kickoffMessage: 'テーマは「{topic}」です。まずは、皆さんのご意見を順番にお聞きしたいと思います。では、{role}の{name}さん。お願いします。',
    presetTeams: {
      ai_providers: "AIモデルプロバイダー",
      tech_giants: "Tech Giants",
      jp_net_commentators: "日本のネット論客",
      us_legendary_hosts: "米歴代有名司会者",
      us_modern_hosts: "米現代TVホスト",
      global_leaders: "各国最高主導者",
      samurai: "武士",
      historical_figures: "偉人達",
      demon_slayer: "鬼滅",
      american_heroes: "アメコミヒーロー",
      geniuses: "天才科学者",
      gods: "神々"
    },
    useOfflineMode: "オフラインモードを使用",
    topicPlaceholderShort: "トピック...",
    interestPlaceholder: "例: コスト効率、安全性...",
    teamNamePlaceholder: "チーム名...",
    noteTitlePlaceholder: "例: システムの背景...",
    done: "完了",
    sessionLog: "セッションログ",
    savePlaceholder: "例: 現在のチーム構成",
    agentsCount: "名",
    agentsLabel: "エージェント:",
    noStats: "まだモデルの使用履歴がありません。",
    speaking: "発言中...",
    startTopic: "トピックを入力して会議を開始",
    gemPromo: "チームを作りたい？Gemをどうぞ。"
};

const frTranslations = {
    ...enTranslations,
    title: "Conseil de Discussion IA",
    subtitle: "Concevez votre équipe de discussion IA parfaite",
    topicLabel: "Quel est l'objectif/sujet de la réunion ?",
    topicPlaceholder: "ex: Créer 3 stratégies marketing pour T4...",
    quickStart: "Démarrage Rapide",
    customize: "Personnaliser",
    back: "Retour",
    save: "Sauvegarder",
    export: "Exporter",
    import: "Importer",
    start: "Commencer la Réunion",
    generating: "Création de l'équipe...",
    agentName: "NOM",
    agentRole: "RÔLE",
    agentInstruction: "PERSONNALITÉ / INSTRUCTION",
    agentInterest: "INTÉRÊT CLÉ / DÉCLENCHEUR",
    autoGenError: "Veuillez entrer un sujet.",
    savedPresets: "ÉQUIPES / MODÈLES",
    selectPreset: "Choisir un modèle...",
    generateAgents: "Générer Agents",
    deletePreset: "Supprimer",
    debugMode: "Mode Débogage",
    debugModeDesc: "Ajouter le nom du modèle aux messages",
    attach: "Joindre",
    moderationOptions: "Options de Modération",
    modOptTitle: "Paramètres de Modération Avancés",
    modOptDesc: "Personnalisez la façon dont le Modérateur IA gère le flux.",
    diamondTitle: "💎 Le Diamant de la Participation",
    diamondDesc: "Le système suit le modèle 'Diamant'. 3 phases :",
    diamondPhase1: "1. Divergence : Générer des idées (Ouverture)",
    diamondPhase2: "2. Groan Zone : Gérer le conflit (Lutte)",
    diamondPhase3: "3. Convergence : Décider (Fermeture)",
    optSixHats: "Six Chapeaux",
    optSixHatsDesc: "Le modérateur impose un mode de pensée (Couleur) à tous.",
    optFistToFive: "Fist to Five (Consensus)",
    optFistToFiveDesc: "Vote de 0 à 5 en phase de convergence.",
    optParkingLot: "Parking Lot",
    optParkingLotDesc: "Mettre de côté les sujets hors-sujet.",
    optReframing: "Recadrage",
    optReframingDesc: "Transformer les critiques en questions constructives.",
    modeOffline: "Mode Hors Ligne",
    offlineTooltip: "Mode démo sans appel API",
    upload: "Télécharger Référence",
    addTextNote: "Ajouter Note",
    textNoteTitle: "Titre",
    textNoteContent: "Coller le texte ici...",
    add: "Ajouter",
    cancel: "Annuler",
    endMeeting: "Terminer",
    endMeetingConfirmTitle: "Terminer la réunion ?",
    endMeetingConfirmDesc: "Voulez-vous générer le compte-rendu ?",
    generateMinutes: "Générer CR",
    generatingMinutes: "Génération en cours...",
    justEnd: "Juste Terminer",
    moderator: "Modérateur",
    saveTeam: "Sauver Équipe",
    modelLabel: "MODÈLE",
    applyToAll: "Appliquer à tous",
    statsLabel: "Statistiques",
    statsCalls: "Appels",
    statsInput: "Entrée",
    statsOutput: "Sortie",
    statsTotal: "Total",
    whiteboardTitle: "Tableau Blanc",
    whiteboardUpdating: "Mise à jour...",
    emptyWhiteboard: "En attente de mise à jour...",
    topic: "Sujet",
    you: "Vous",
    thinking: "Réfléchit...",
    useOfflineMode: "Utiliser Mode Hors Ligne",
    topicPlaceholderShort: "Sujet...",
    interestPlaceholder: "ex: Coût, Sécurité...",
    teamNamePlaceholder: "Nom de l'équipe...",
    noteTitlePlaceholder: "ex: Contexte",
    done: "Fait",
    sessionLog: "Journal",
    savePlaceholder: "ex: Équipe Actuelle",
    agentsCount: "agents",
    agentsLabel: "Agents:",
    speaking: "Parle...",
    startTopic: "Entrez un sujet pour commencer",
    gemPromo: "Votre équipe ? Utilisez Gem.",
    modelNames: {
        'gemini-3-pro-preview': 'Gemini 3 Pro (Haute Qualité)',
        'gemini-2.5-pro': 'Gemini 2.5 Pro (Équilibré)',
        'gemini-2.5-flash': 'Gemini 2.5 Flash (Rapide)',
        'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite (Économique)',
        'gemini-2.0-flash-lite-preview-02-05': 'Gemini 2.0 Flash Lite (Secours)'
    }
};

const deTranslations = {
    ...enTranslations,
    title: "KI-Diskussionsboard",
    subtitle: "Entwerfen Sie Ihr perfektes KI-Team",
    topicLabel: "Was ist das Ziel/Thema?",
    topicPlaceholder: "z.B. 3 Marketingstrategien entwickeln...",
    quickStart: "Schnellstart",
    customize: "Anpassen",
    back: "Zurück",
    save: "Speichern",
    export: "Exportieren",
    import: "Importieren",
    start: "Starten",
    generating: "Team wird erstellt...",
    agentName: "NAME",
    agentRole: "ROLLE",
    agentInstruction: "PERSÖNLICHKEIT",
    agentInterest: "INTERESSE / AUSLÖSER",
    autoGenError: "Bitte Thema eingeben.",
    savedPresets: "GESPEICHERTE TEAMS",
    selectPreset: "Vorlage wählen...",
    generateAgents: "Agenten Generieren",
    deletePreset: "Löschen",
    debugMode: "Debug-Modus",
    debugModeDesc: "Modellnamen in Nachrichten anzeigen",
    attach: "Anhängen",
    moderationOptions: "Moderationsoptionen",
    modOptTitle: "Erweiterte Moderation",
    modOptDesc: "Passen Sie den KI-Moderator an.",
    diamondTitle: "💎 Diamant der Partizipation",
    diamondDesc: "Das System folgt dem 'Diamant'-Modell. 3 Phasen:",
    diamondPhase1: "1. Divergenz: Ideen generieren (Offen)",
    diamondPhase2: "2. Groan Zone: Konflikte bearbeiten",
    diamondPhase3: "3. Konvergenz: Entscheidung (Geschlossen)",
    optSixHats: "Sechs Denkhüte",
    optSixHatsDesc: "Moderator bestimmt den Denkmodus (Farbe).",
    optFistToFive: "Fist to Five (Konsens)",
    optFistToFiveDesc: "0-5 Abstimmung in der Konvergenzphase.",
    optParkingLot: "Themenspeicher",
    optParkingLotDesc: "Abschweifungen parken.",
    optReframing: "Reframing",
    optReframingDesc: "Kritik in Fragen umwandeln.",
    modeOffline: "Offline-Modus",
    offlineTooltip: "Demo-Modus ohne API",
    upload: "Referenz hochladen",
    addTextNote: "Notiz hinzufügen",
    textNoteTitle: "Titel",
    textNoteContent: "Text hier einfügen...",
    add: "Hinzufügen",
    cancel: "Abbrechen",
    endMeeting: "Beenden",
    endMeetingConfirmTitle: "Meeting beenden?",
    endMeetingConfirmDesc: "Protokoll erstellen?",
    generateMinutes: "Protokoll",
    generatingMinutes: "Erstelle...",
    justEnd: "Nur Beenden",
    moderator: "Moderator",
    saveTeam: "Team Speichern",
    modelLabel: "MODELL",
    applyToAll: "Auf alle anwenden",
    statsLabel: "Statistiken",
    statsCalls: "Aufrufe",
    statsInput: "Input",
    statsOutput: "Output",
    statsTotal: "Gesamt",
    whiteboardTitle: "Whiteboard",
    whiteboardUpdating: "Aktualisiere...",
    emptyWhiteboard: "Warte auf Updates...",
    topic: "Thema",
    you: "Du",
    thinking: "Denkt nach...",
    useOfflineMode: "Offline-Modus nutzen",
    topicPlaceholderShort: "Thema...",
    interestPlaceholder: "z.B. Kosten, Sicherheit...",
    teamNamePlaceholder: "Teamname...",
    noteTitlePlaceholder: "z.B. Kontext",
    done: "Fertig",
    sessionLog: "Protokoll",
    savePlaceholder: "z.B. Aktuelles Team",
    agentsCount: "Agenten",
    agentsLabel: "Agenten:",
    speaking: "Spricht...",
    startTopic: "Thema eingeben zum Starten",
    gemPromo: "Ihr Team? Nutzen Sie Gem.",
    modelNames: {
        'gemini-3-pro-preview': 'Gemini 3 Pro (Hohe Qualität)',
        'gemini-2.5-pro': 'Gemini 2.5 Pro (Ausgewogen)',
        'gemini-2.5-flash': 'Gemini 2.5 Flash (Schnell)',
        'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite (Kostengünstig)',
        'gemini-2.0-flash-lite-preview-02-05': 'Gemini 2.0 Flash Lite (Backup)'
    }
};

const itTranslations = {
    ...enTranslations,
    title: "Scheda Discussione IA",
    subtitle: "Progetta il tuo team IA perfetto",
    topicLabel: "Qual è l'obiettivo/argomento?",
    topicPlaceholder: "es. 3 strategie di marketing...",
    quickStart: "Avvio Rapido",
    customize: "Personalizza",
    back: "Indietro",
    save: "Salva",
    export: "Esporta",
    import: "Importa",
    start: "Inizia",
    generating: "Creazione team...",
    agentName: "NOME",
    agentRole: "RUOLO",
    agentInstruction: "PERSONALITÀ",
    agentInterest: "INTERESSE",
    autoGenError: "Inserisci un argomento.",
    savedPresets: "TEAM SALVATI",
    selectPreset: "Scegli modello...",
    generateAgents: "Genera Agenti",
    deletePreset: "Elimina",
    debugMode: "Modalità Debug",
    debugModeDesc: "Mostra nome modello nei messaggi",
    attach: "Allega",
    moderationOptions: "Opzioni Moderazione",
    modOptTitle: "Impostazioni Avanzate",
    modOptDesc: "Personalizza il Moderatore IA.",
    diamondTitle: "💎 Diamante della Partecipazione",
    diamondDesc: "Il sistema segue il modello 'Diamante'. 3 fasi:",
    diamondPhase1: "1. Divergenza: Generare idee",
    diamondPhase2: "2. Groan Zone: Gestire conflitti",
    diamondPhase3: "3. Convergenza: Decisione",
    optSixHats: "Sei Cappelli",
    optSixHatsDesc: "Il moderatore imposta il modo di pensare.",
    optFistToFive: "Fist to Five (Consenso)",
    optFistToFiveDesc: "Voto 0-5 per convergere.",
    optParkingLot: "Parcheggio Idee",
    optParkingLotDesc: "Parcheggiare i fuori tema.",
    optReframing: "Reframing",
    optReframingDesc: "Trasformare critiche in domande.",
    modeOffline: "Modalità Offline",
    offlineTooltip: "Demo senza API",
    upload: "Carica Riferimento",
    addTextNote: "Aggiungi Nota",
    textNoteTitle: "Titolo",
    textNoteContent: "Incolla testo...",
    add: "Aggiungi",
    cancel: "Annulla",
    endMeeting: "Termina",
    endMeetingConfirmTitle: "Terminare riunione?",
    endMeetingConfirmDesc: "Generare verbale?",
    generateMinutes: "Genera Verbale",
    generatingMinutes: "Generazione...",
    justEnd: "Termina e basta",
    moderator: "Moderator",
    saveTeam: "Salva Team",
    modelLabel: "MODELLO",
    applyToAll: "Applica a tutti",
    statsLabel: "Statistiche",
    statsCalls: "Chiamate",
    statsInput: "Input",
    statsOutput: "Output",
    statsTotal: "Totale",
    whiteboardTitle: "Lavagna",
    whiteboardUpdating: "Aggiornamento...",
    emptyWhiteboard: "In attesa di aggiornamenti...",
    topic: "Argomento",
    you: "Tu",
    thinking: "Pensa...",
    useOfflineMode: "Usa Offline",
    topicPlaceholderShort: "Argomento...",
    interestPlaceholder: "es. Costi, Sicurezza...",
    teamNamePlaceholder: "Nome Team...",
    noteTitlePlaceholder: "es. Contesto",
    done: "Fatto",
    sessionLog: "Registro",
    savePlaceholder: "es. Team Attuale",
    agentsCount: "agenti",
    agentsLabel: "Agenti:",
    speaking: "Parla...",
    startTopic: "Inserisci argomento per iniziare",
    gemPromo: "La tua squadra? Usa Gem.",
    modelNames: {
        'gemini-3-pro-preview': 'Gemini 3 Pro (Alta Qualità)',
        'gemini-2.5-pro': 'Gemini 2.5 Pro (Bilanciato)',
        'gemini-2.5-flash': 'Gemini 2.5 Flash (Veloce)',
        'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite (Economico)',
        'gemini-2.0-flash-lite-preview-02-05': 'Gemini 2.0 Flash Lite (Backup)'
    }
};

const zhTranslations = {
    ...enTranslations,
    title: "AI 讨论板",
    subtitle: "设计您的完美 AI 讨论团队",
    topicLabel: "会议的目标/主题是什么？",
    topicPlaceholder: "例如：制定3个营销策略...",
    quickStart: "快速开始",
    customize: "自定义",
    back: "返回",
    save: "保存",
    export: "导出",
    import: "导入",
    start: "开始会议",
    generating: "正在组建团队...",
    agentName: "姓名",
    agentRole: "角色",
    agentInstruction: "性格 / 指令",
    agentInterest: "关键兴趣 / 触发点",
    autoGenError: "请输入主题。",
    savedPresets: "保存的团队",
    selectPreset: "选择模板...",
    generateAgents: "生成代理",
    deletePreset: "删除",
    debugMode: "调试模式",
    debugModeDesc: "在消息中显示模型名称",
    attach: "附件",
    moderationOptions: "主持选项",
    modOptTitle: "高级引导设置",
    modOptDesc: "自定义 AI 主持人的控制方式。",
    diamondTitle: "💎 参与钻石模型",
    diamondDesc: "系统遵循“钻石”模型。分为3个阶段：",
    diamondPhase1: "1. 发散：产生想法（开放）",
    diamondPhase2: "2. 呻吟区：处理冲突（挣扎）",
    diamondPhase3: "3. 收敛：做出决定（关闭）",
    optSixHats: "六顶思考帽",
    optSixHatsDesc: "主持人强制指定思考模式（颜色）。",
    optFistToFive: "五指投票 (共识检查)",
    optFistToFiveDesc: "收敛阶段进行 0-5 投票。",
    optParkingLot: "停车场",
    optParkingLotDesc: "暂时搁置偏离主题的想法。",
    optReframing: "重构 (Reframing)",
    optReframingDesc: "将批评转化为建设性问题。",
    modeOffline: "离线模式",
    offlineTooltip: "无 API 的演示模式",
    upload: "上传参考资料",
    addTextNote: "添加笔记",
    textNoteTitle: "标题",
    textNoteContent: "在此粘贴文本...",
    add: "添加",
    cancel: "取消",
    endMeeting: "结束会议",
    endMeetingConfirmTitle: "结束会议？",
    endMeetingConfirmDesc: "是否生成会议纪要？",
    generateMinutes: "生成纪要",
    generatingMinutes: "正在生成...",
    justEnd: "直接结束",
    moderator: "主持人",
    saveTeam: "保存团队",
    modelLabel: "模型",
    applyToAll: "应用到所有",
    statsLabel: "统计",
    statsCalls: "调用",
    statsInput: "输入",
    statsOutput: "输出",
    statsTotal: "总计",
    whiteboardTitle: "白板",
    whiteboardUpdating: "更新中...",
    emptyWhiteboard: "等待更新...",
    topic: "主题",
    you: "你",
    thinking: "思考中...",
    useOfflineMode: "使用离线模式",
    topicPlaceholderShort: "主题...",
    interestPlaceholder: "例如：成本、安全...",
    teamNamePlaceholder: "团队名称...",
    noteTitlePlaceholder: "例如：背景信息",
    done: "完成",
    sessionLog: "会话日志",
    savePlaceholder: "例如：当前团队快照",
    agentsCount: "代理",
    agentsLabel: "代理：",
    speaking: "发言中...",
    startTopic: "输入主题以开始",
    gemPromo: "想要组建团队？请使用 Gem。",
    modelNames: {
        'gemini-3-pro-preview': 'Gemini 3 Pro (高质量)',
        'gemini-2.5-pro': 'Gemini 2.5 Pro (平衡)',
        'gemini-2.5-flash': 'Gemini 2.5 Flash (快速)',
        'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite (低成本)',
        'gemini-2.0-flash-lite-preview-02-05': 'Gemini 2.0 Flash Lite (备用)'
    }
};

const koTranslations = {
    ...enTranslations,
    title: "AI 토론 보드",
    subtitle: "완벽한 AI 토론 팀을 설계하세요",
    topicLabel: "회의 목표/주제는 무엇입니까?",
    topicPlaceholder: "예: 마케팅 전략 3가지 수립...",
    quickStart: "빠른 시작",
    customize: "사용자 지정",
    back: "뒤로",
    save: "저장",
    export: "내보내기",
    import: "가져오기",
    start: "회의 시작",
    generating: "팀 구성 중...",
    agentName: "이름",
    agentRole: "역할",
    agentInstruction: "성격 / 지침",
    agentInterest: "주요 관심사 / 트리거",
    autoGenError: "주제를 입력하세요.",
    savedPresets: "저장된 팀",
    selectPreset: "템플릿 선택...",
    generateAgents: "에이전트 생성",
    deletePreset: "삭제",
    debugMode: "디버그 모드",
    debugModeDesc: "메시지에 모델 이름 표시",
    attach: "첨부",
    moderationOptions: "중재 옵션",
    modOptTitle: "고급 중재 설정",
    modOptDesc: "AI 사회자의 진행 방식을 설정합니다.",
    diamondTitle: "💎 참여의 다이아몬드",
    diamondDesc: "시스템은 '다이아몬드' 모델을 따릅니다. 3단계:",
    diamondPhase1: "1. 발산: 아이디어 도출 (열기)",
    diamondPhase2: "2. 신음 구간: 갈등 조정 (고민)",
    diamondPhase3: "3. 수렴: 의사 결정 (닫기)",
    optSixHats: "여섯 가지 생각 모자",
    optSixHatsDesc: "사회자가 사고 방식(색상)을 지정합니다.",
    optFistToFive: "주먹 오 (합의 확인)",
    optFistToFiveDesc: "수렴 단계에서 0-5 투표 진행.",
    optParkingLot: "주차장 (보류)",
    optParkingLotDesc: "주제에서 벗어난 아이디어를 보류합니다.",
    optReframing: "리프레이밍",
    optReframingDesc: "비판을 건설적인 질문으로 바꿉니다.",
    modeOffline: "오프라인 모드",
    offlineTooltip: "API 없는 데모 모드",
    upload: "참료 자료 업로드",
    addTextNote: "메모 추가",
    textNoteTitle: "제목",
    textNoteContent: "여기에 텍스트 붙여넣기...",
    add: "추가",
    cancel: "취소",
    endMeeting: "회의 종료",
    endMeetingConfirmTitle: "회의를 종료하시겠습니까?",
    endMeetingConfirmDesc: "회의록을 생성하시겠습니까?",
    generateMinutes: "회의록 생성",
    generatingMinutes: "생성 중...",
    justEnd: "그냥 종료",
    moderator: "사회자",
    saveTeam: "팀 저장",
    modelLabel: "모델",
    applyToAll: "모두에게 적용",
    statsLabel: "통계",
    statsCalls: "호출",
    statsInput: "입력",
    statsOutput: "출력",
    statsTotal: "합계",
    whiteboardTitle: "화이트보드",
    whiteboardUpdating: "업데이트 중...",
    emptyWhiteboard: "업데이트 대기 중...",
    topic: "주제",
    you: "나",
    thinking: "생각 중...",
    useOfflineMode: "오프라인 모드 사용",
    topicPlaceholderShort: "주제...",
    interestPlaceholder: "예: 비용, 안전...",
    teamNamePlaceholder: "팀 이름...",
    noteTitlePlaceholder: "예: 시스템 배경",
    done: "완료",
    sessionLog: "세션 로그",
    savePlaceholder: "예: 현재 팀 구성",
    agentsCount: "명",
    agentsLabel: "에이전트:",
    speaking: "발언 중...",
    startTopic: "주제를 입력하여 시작",
    gemPromo: "팀을 만들고 싶으세요? Gem을 사용하세요.",
    modelNames: {
        'gemini-3-pro-preview': 'Gemini 3 Pro (고품질)',
        'gemini-2.5-pro': 'Gemini 2.5 Pro (균형)',
        'gemini-2.5-flash': 'Gemini 2.5 Flash (빠름)',
        'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite (저비용)',
        'gemini-2.0-flash-lite-preview-02-05': 'Gemini 2.0 Flash Lite (백업)'
    }
};

const ptTranslations = {
    ...enTranslations,
    title: "Quadro de Discussão IA",
    subtitle: "Projete sua equipe de discussão IA perfeita",
    topicLabel: "Qual é o objetivo/tópico?",
    topicPlaceholder: "ex: Criar 3 estratégias de marketing...",
    quickStart: "Início Rápido",
    customize: "Personalizar",
    back: "Voltar",
    save: "Salvar",
    export: "Exportar",
    import: "Importar",
    start: "Iniciar",
    generating: "Criando equipe...",
    agentName: "NOME",
    agentRole: "FUNÇÃO",
    agentInstruction: "PERSONALIDADE",
    agentInterest: "INTERESSE",
    autoGenError: "Digite um tópico.",
    savedPresets: "TIMES SALVOS",
    selectPreset: "Escolher modelo...",
    generateAgents: "Gerar Agentes",
    deletePreset: "Excluir",
    debugMode: "Modo Debug",
    debugModeDesc: "Mostrar modelo nas mensagens",
    attach: "Anexar",
    moderationOptions: "Opções de Moderação",
    modOptTitle: "Configurações Avançadas",
    modOptDesc: "Personalize o Moderador IA.",
    diamondTitle: "💎 Diamante da Participação",
    diamondDesc: "O sistema segue o modelo 'Diamante'. 3 fases:",
    diamondPhase1: "1. Divergência: Gerar ideias (Abrir)",
    diamondPhase2: "2. Groan Zone: Gerir conflitos",
    diamondPhase3: "3. Convergência: Decisão (Fechar)",
    optSixHats: "Seis Chapéus",
    optSixHatsDesc: "Moderador define o modo de pensar (Cor).",
    optFistToFive: "Fist to Five (Consenso)",
    optFistToFiveDesc: "Votação 0-5 na fase de convergência.",
    optParkingLot: "Estacionamento",
    optParkingLotDesc: "Guardar ideias fora do tópico.",
    optReframing: "Reenquadramento",
    optReframingDesc: "Transformar críticas em perguntas.",
    modeOffline: "Modo Offline",
    offlineTooltip: "Modo demo sem API",
    upload: "Carregar Referência",
    addTextNote: "Adicionar Nota",
    textNoteTitle: "Título",
    textNoteContent: "Cole o texto aqui...",
    add: "Adicionar",
    cancel: "Cancelar",
    endMeeting: "Encerrar",
    endMeetingConfirmTitle: "Encerrar reunião?",
    endMeetingConfirmDesc: "Gerar ata?",
    generateMinutes: "Gerar Ata",
    generatingMinutes: "Gerando...",
    justEnd: "Apenas Encerrar",
    moderator: "Moderador",
    saveTeam: "Salvar Time",
    modelLabel: "MODELO",
    applyToAll: "Aplicar a todos",
    statsLabel: "Estatísticas",
    statsCalls: "Chamadas",
    statsInput: "Entrada",
    statsOutput: "Saída",
    statsTotal: "Total",
    whiteboardTitle: "Quadro Branco",
    whiteboardUpdating: "Atualizando...",
    emptyWhiteboard: "Aguardando atualizações...",
    topic: "Tópico",
    you: "Você",
    thinking: "Pensando...",
    useOfflineMode: "Usar Modo Offline",
    topicPlaceholderShort: "Tópico...",
    interestPlaceholder: "ex: Custo, Segurança...",
    teamNamePlaceholder: "Nome do Time...",
    noteTitlePlaceholder: "ex: Contexto",
    done: "Concluído",
    sessionLog: "Log",
    savePlaceholder: "ex: Time Atual",
    agentsCount: "agentes",
    agentsLabel: "Agentes:",
    speaking: "Falando...",
    startTopic: "Digite um tópico para iniciar",
    gemPromo: "Sua equipe? Use o Gem.",
    modelNames: {
        'gemini-3-pro-preview': 'Gemini 3 Pro (Alta Qualidade)',
        'gemini-2.5-pro': 'Gemini 2.5 Pro (Equilibrado)',
        'gemini-2.5-flash': 'Gemini 2.5 Flash (Rápido)',
        'gemini-2.5-flash-lite': 'Gemini 2.5 Flash Lite (Baixo Custo)',
        'gemini-2.0-flash-lite-preview-02-05': 'Gemini 2.0 Flash Lite (Reserva)'
    }
};

export const TRANSLATIONS: Record<string, typeof enTranslations> = {
  en: enTranslations,
  ja: jaTranslations,
  fr: frTranslations,
  de: deTranslations,
  it: itTranslations,
  zh: zhTranslations,
  ko: koTranslations,
  pt: ptTranslations
};
